### ISSUE TITLE
The main.py file got corrupt and now it doesnt work. How can i fix this

### ISSUE THREAD

**Issue by domoosu** [thnikk/trinketM0#1]
My main.py file got corrupted and i dont know what the code was that was there already on the osu basic keypad are you able to send me the main.py file so i can use the product again.

**Comment by thnikk** [comment]
Please follow my reprogramming guide here: http://docs.thnikk.moe/en/latest/program.html

The keypad should not be using any python file, corrupted or not. Since your issue is not directly with this repository, I am closing it. If you have any questions about the guide, please message me on Etsy.
